# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'NendSDK_Swift_Sample' do
# pod 'NendSDK_iOS'
end

target 'NendSDK_Sample' do
# pod 'NendSDK_iOS'
end

